


isBull(offset = 0) =>
  close[offset] > open[offset]

isBear(offset = 0) =>
  close[offset] < open[offset]

bodySize(offset = 0) =>
    math.abs(close[offset] - open[offset])

valueToPercent(value, index = 0) =>
    value / open[index] * 100.

proportionPercent(baseValue, propotionValue) =>
    propotionValue / baseValue * 100.
    
approxEq(value, target, tollerance) =>
    math.abs(value - target) < tollerance
        

getConditionalText(condition, txt, prefix) =>
    condition ? ( prefix + txt ) : ""

getNumberText(num) =>
    num < 1 ? ("0" + str.tostring(num, "#.0")) : str.tostring(num, "#.0")
    
    
getRiskRewardTargetFromSize (min, max, rrrTarget) =>
  sizePercent = (max - min) / min * 100,
  rrrSL = sizePercent / 2 + rrrFees,
  rrrTP = rrrSL * rrrTarget + rrrFees,
  rrrTargetText = rrrHint ? ("1:" + getNumberText((rrrSL + rrrTP)/rrrSL)) : "",
  percentText = str.tostring(sizePercent, format.percent),
  [percentText, rrrTargetText]

getPercentFromSize (min, max) =>
  sizePercent = (max - min) / min * 100,
  sizePercent


getMaxRatioText (min, max, max_value) =>
  sizePercent = (max - min) / min * 100,
  center = (max - min) / 2,
  maxPercent = math.abs(max_value - center) / min * 100,
  sl = sizePercent / 2,
  "1:" + getNumberText(maxPercent + sl)
  
  