
// =============== FVG ===============

fvgMaxAge = input.int(72, "FVG-Maximum Age in Hours", group="FVG Einstellungen")
fvgAlarmLevel = input.float(0.75, "FVG-Near Level", step=0.1, group="FVG Einstellungen")
fvgTouchThreshold = input.float(0.1, "FVG-Touch Threshold", minval=0.0, maxval=1, step=0.01, group="FVG Einstellungen")

fvgMaxAgeBars = fvgMaxAge * hourBars

fvgInSizeLimitMode = input.string("percent", "FVG-GrößenLimit", options=["percent", "atr"], group="FVG Einstellungen")
fvgAtrLength = input.int(14, "FVG-ATR Length", group="FVG Einstellungen")
fvgAtrFactor = input.float(0.5, "FVG-Threshold Factor", minval=0.0, step=0.1, group="FVG Einstellungen")
fvgPercentThreshold = input.float(0.5, "FVG-Percent-Threshold", minval=0.0, step=0.1, group="FVG Einstellungen")

rrrHint = input.bool(true, "RiskReward Hint", group="FVG Risk/Reward")
rrrFees = input.float(0.04, "Calculation Fees", minval=0.0, step=0.1, group="FVG Risk/Reward")
fvgRrrTarget = input.float(3, "Desired Range", minval=0.0, step=0.1, group="FVG Risk/Reward")
