  
//-----------------------------------------------------------------------------
// FVG - detection/display
//-----------------------------------------------------------------------------


var fvg_lastStartTime = 0

var fvg_records = array.new<Fvg>(0)

if isNewHour
    new_fvg = request.security(syminfo.tickerid, "60", fvgDetect())

    if not na(new_fvg) and new_fvg.startTime != fvg_lastStartTime
        new_fvg.startIndex := bar_index - 2 * hourBars
        fvg_lastStartTime := new_fvg.startTime

        info = createFvgFvgInfo(new_fvg)
        draw = createFvgDraw(new_fvg, info)

        fvg = Fvg.new(new_fvg, draw, info)
        fvg_records.unshift(fvg)

//-----------------------------------------------------------------------------
// FVG - Mitigation Logik
//-----------------------------------------------------------------------------
// Boxen rechts verschieben oder "abschließen"

bool fvgShowEnter = false
bool fvgShowNear = false
string fvgShowEnterInfo = na
string fvgShowNearInfo = na
bool fvgShowInvalidated = false
// 
// float alarmMin = 0
// float alarmMax = 0
// bool alarmBull = false
// 

if fvg_records.size() > 0
    for i = 0 to fvg_records.size() -1
        fvg = fvg_records.get(i)

        if not fvg.isDead
            [_fvg, expired, invalidated, entered, near] = fvgPerformStep(fvg)
            fvg := _fvg

            if entered
                fvgShowEnter := true
                fvgShowEnterInfo := getFvgEnterText(fvg)
                fvgSetEnterText(fvg)

            if near
                fvgShowNear := true
                fvgShowNearInfo := getFvgEnterText(fvg)
                fvgSetEnterText(fvg)

            if invalidated
                fvgShowInvalidated := true
                fvgSetInvalidated(fvg)

            if expired or invalidated
                fvg.isDead := true
            else
                box.set_right(fvg.draw.drawBox, bar_index)
                line.set_x2(fvg.draw.centerLine, bar_index)
                line.set_x2(fvg.draw.alarmLine, bar_index)

        fvg_records.set(i, fvg)

if fvg_records.size() > 0
    for i = fvg_records.size()-1 to 0
        fvg = fvg_records.get(i)
        if box.get_left(fvg.draw.drawBox) < bar_index - fvgMaxAgeBars
            box.delete(fvg.draw.drawBox)
            line.delete(fvg.draw.centerLine)
            line.delete(fvg.draw.alarmLine)
            label.delete(fvg.draw.infoLabel)
            fvg_records.remove(i)
        
// 
// 
plotshape(fvgShowEnter, style=shape.triangledown, location=location.abovebar, color=color.gray, size=size.tiny)
plotshape(fvgShowInvalidated, style=shape.xcross, location=location.abovebar, color=color.red, size=size.tiny)


//-----------------------------------------------------------------------------}
//FVG - Alerts
//-----------------------------------------------------------------------------{

//alertcondition(fvgShowEnter, 'FVG-enter', '{{ticker}} FairValueGap ENTER')
//alertcondition(fvgShowNear, 'FVG-near', '{{ticker}} FairValueGap NEAR')
//alertcondition(fvgShowInvalidated, 'FVG-invalid', '{{ticker}} FairValueGap invalidated')

if fvgShowEnter
    alert(syminfo.ticker + "FVG Entered " + fvgShowEnterInfo, alert.freq_once_per_bar)
else if fvgShowNear
    alert(syminfo.ticker + "FVG Near " + fvgShowNearInfo, alert.freq_once_per_bar)
   
