  
//-----------------------------------------------------------------------------
// FVG - Detection and display
//-----------------------------------------------------------------------------


var fvg_lastStartTime = 0
var fvg_records = array.new<Fvg>(0)

bool fvgDetected = false
string fvgDetectedText = ""

if isNewHour
    new_fvg = request.security(syminfo.tickerid, "60", fvgDetect())

    if not na(new_fvg) and new_fvg.startTime != fvg_lastStartTime
        new_fvg.startIndex := bar_index - 2 * hourBars
        fvg_lastStartTime := new_fvg.startTime

        state = createFvgFvgState(new_fvg)
        draw = createFvgDraw(new_fvg, state)

        fvg = Fvg.new(new_fvg, draw, state)
        fvg_records.unshift(fvg)

        fvgDetected := true
        fvgDetectedText := fvgGetDetectedText(fvg)

//-----------------------------------------------------------------------------
// FVG - Mitigation Logik
//-----------------------------------------------------------------------------
// Boxen rechts verschieben oder "abschließen"

bool fvgShowEnter = false
bool fvgShowNear = false
string fvgShowEnterText = na
string fvgShowNearText = na
bool fvgShowInvalidated = false
// 
// float alarmMin = 0
// float alarmMax = 0
// bool alarmBull = false
// 

if fvg_records.size() > 0
    for i = 0 to fvg_records.size() -1
        fvg = fvg_records.get(i)

        if not fvg.state.isDead and (fvgDebugStartTime == 0 or fvg.def.startTime == fvgDebugStartTime)
            [state, actionInvalidate, actionEntered, actionNear] = fvgPerformStep(fvg)
            fvg.state := state

            if actionEntered
                fvgShowEnter := true
                fvgShowEnterText := fvgGetEnteredText(fvg)
                fvgSetEnterText(fvg)

            if actionNear
                fvgShowNear := true
                fvgShowNearText := fvgGetNearText(fvg)
                fvgSetEnterText(fvg)

            if actionInvalidate
                fvgShowInvalidated := true
                fvgDrawSetInvalidated(fvg.draw, fvg.def)

            if not state.isDead
                box.set_right(fvg.draw.drawBox, bar_index)
                line.set_x2(fvg.draw.centerLine, bar_index)
                line.set_x2(fvg.draw.alarmLine, bar_index)

        fvg_records.set(i, fvg)

if fvg_records.size() > 0
    for i = fvg_records.size()-1 to 0
        fvg = fvg_records.get(i)
        if box.get_left(fvg.draw.drawBox) < bar_index - fvgMaxAgeBars
            fvgDrawRemove(fvg.draw)
            fvg_records.remove(i)
        
// 
// 
plotshape(fvgShowEnter, style=shape.triangledown, location=location.abovebar, color=color.gray, size=size.tiny)
plotshape(fvgShowInvalidated, style=shape.xcross, location=location.abovebar, color=color.red, size=size.tiny)
plotshape(fvgShowNear, style=shape.flag, location=location.abovebar, color=color.lime, size=size.tiny)


//-----------------------------------------------------------------------------}
//FVG - Alerts
//-----------------------------------------------------------------------------{

//alertcondition(fvgShowEnter, 'FVG-enter', '{{ticker}} FairValueGap ENTER')
//alertcondition(fvgShowNear, 'FVG-near', '{{ticker}} FairValueGap NEAR')
//alertcondition(fvgShowInvalidated, 'FVG-invalid', '{{ticker}} FairValueGap invalidated')

if fvgShowEnter
    alert(syminfo.ticker + "FVG Entered " + fvgShowEnterText, alert.freq_once_per_bar)
else if fvgShowNear
    alert(syminfo.ticker + "FVG Near " + fvgShowNearText, alert.freq_once_per_bar)
else if fvgDetected
    alert(syminfo.ticker + "FVG detected " + fvgDetectedText, alert.freq_once_per_bar)
    
