

var lsob_lastStartTime = 0

var lsob_records = array.new<Lsob>(0)

if losbShow and isNewHour
    new_lsob = request.security(syminfo.tickerid, "60", lsobDetect())

    if not na(new_lsob) and new_lsob.startTime != lsob_lastStartTime //  and new_lsob.startTime == 1750244400000
        // label.new(bar_index, high, "Detected", size=size.small, color=color.silver, textcolor=color.black, style=label.style_label_down)
        new_lsob.startIndex := bar_index
        lsob_lastStartTime := new_lsob.startTime

        draw = createLsobDraw(new_lsob)

        lsob = Lsob.new(new_lsob, draw)
        lsob_records.unshift(lsob)

if lsob_records.size() > 0
    for i = 0 to lsob_records.size() -1
        lsob = lsob_records.get(i)

        if not lsob.isDead
            [_lsob, entered, near] = lsobPerformStep(lsob)
            lsob := _lsob

            // label.new(bar_index, high, str.tostring(low)+" "+str.tostring(lsob.def.min), size=size.small, color=color.silver, textcolor=color.black, style=label.style_label_down)

            // if entered
            //     fvgShowEnter := true
            //     fvgShowEnterInfo := fvgGetEnterText(lsob)
            //     fvgSetEnterText(lsob)

            // if near
            //     fvgShowNear := true
            //     fvgShowNearInfo := fvgGetEnterText(lsob)
            //     fvgSetEnterText(lsob)

            if lsob.wasInvalidated
                box.set_bgcolor(lsob.draw.drawBox, color.white)

            if lsob.isDelete or lsob.wasInvalidated
                lsob.isDead := true
            else
                box.set_right(lsob.draw.drawBox, bar_index)
                if lsob.wasLeaved
                    box.set_bgcolor(lsob.draw.drawBox, color.silver)

        lsob_records.set(i, lsob)
        
if lsob_records.size() > 0
    for i = lsob_records.size()-1 to 0
        lsob = lsob_records.get(i)
        if lsob.isDelete or box.get_left(lsob.draw.drawBox) < bar_index - lsobMaxAgeBars
            box.delete(lsob.draw.drawBox)
            label.delete(lsob.draw.infoLabel)
            lsob_records.remove(i)