//@version=6
indicator("Fair Value Gangster", "FV-Gang", overlay=true, max_lines_count=500, max_boxes_count=200)

//DEFINE: FVG:true
//DEFINE: LSOB:true
//DEFINE: RSI:true
//DEFINE: HINTS:true
//DEFINE: SBS:true
//DEFINE: LIGRAP:true


//------------------------------------------------------------------------------
//Settings
//-----------------------------------------------------------------------------

//IMPORT IF(FVG) fvg.settings.pine
//IMPORT IF(LSOB) lsob.settings.pine
//IMPORT IF(SBS) side-by-side.settings.pine
//IMPORT IF(RSI) rsi-div.settings.pine
//IMPORT IF(LIGRAP) liqui-grap.settings.pine
//IMPORT settings.pine


//IMPORT commons.pine

//IMPORT IF(FVG) fvg.functions.pine
//IMPORT IF(FVG) fvg.main.pine


//IMPORT IF(LSOB) lsob.functions.pine
//IMPORT IF(LSOB) lsob.main.pine
//IMPORT IF(LSOB) lsob.main-check.pine

//IMPORT IF(SBS) side-by-side.pine
//IMPORT IF(RSI) rsi-div.main.pine
//IMPORT IF(LIGRAP) liqui-grap.main.pine

//IMPORT IF(HINTS) emas.pine
//IMPORT IF(HINTS) vwap.pine

