
AlarmDefinition lsobTouchedAlarm = na


// LSOBS Überprüfen
if lsob_records.size() > 0
    for i = lsob_records.size()-1 to 0
        lsob = lsob_records.get(i)

        [state, action] = lsobCheckInBar(lsob)

        if action == "activated"
            activateLsobDraw(lsob.def, lsob.draw)
        else if action == "touch"
            lsobTouchedAlarm := createAlarm( lsobGetTochedText(lsob), lsob.def.isBull ? "bottom" : "top")

        if action == "touch" or state.phase != 'closed'
            mitigateLsobDraw(lsob.draw)

        lsob.state := state
        lsob_records.set(i, lsob)


if lsob_records.size() > 0
    for i = lsob_records.size()-1 to 0
        lsob = lsob_records.get(i)
        //debugLabelOffset := debugLabel(debugLabelOffset, str.tostring(lsob.state.toDelete)+" "+str.tostring(lsob.def.startIndex))
        if lsob.state.toDelete
            removeLsobDraw(lsob.draw)
            lsob_records.remove(i)

if not na(lsobTouchedAlarm)
    showAlarm(lsobTouchedAlarm)
    alert(lsobTouchedAlarm.alarmText, alert.freq_once_per_bar)
