

var lsob_lastStartTime = 0
var lsob_records = array.new<Lsob>(0)

if losbShow and isNewHour
    new_lsob = request.security(syminfo.tickerid, "60", lsobDetect("1h"))

    if not na(new_lsob) and new_lsob.startTime != lsob_lastStartTime //  and new_lsob.startTime == 1750244400000
        // label.new(bar_index, high, "Detected", size=size.small, color=color.silver, textcolor=color.black, style=label.style_label_down)
        new_lsob.startIndex := bar_index
        lsob_lastStartTime := new_lsob.startTime

        lsob = Lsob.new(new_lsob, createLsobDraw(new_lsob), createLsobState())
        lsob_records.unshift(lsob)
 
        // DEBUG
        // debugText = (new_lsob.isBull?'u ':'d ') + str.tostring(new_lsob.min)+"-"+str.tostring(new_lsob.max) + " " + str.tostring(new_lsob.startIndex)
        //debugLabelOffset := debugLabel(debugLabelOffset, debugText)

//debugLabelOffset := debugLabel(debugLabelOffset, str.tostring(lsob_records.size()))
//debugLabelOffset := debugLabel(debugLabelOffset, str.tostring(bar_index))
