

var lsob_records = array.new<Lsob>(0)


[lsob1h_l, lsob1h_h] = request.security(syminfo.tickerid, "60", getLowHigh())
[lsob4h_l, lsob4h_h] = request.security(syminfo.tickerid, "240", getLowHigh())

if losbShow and isNewHour
    new_lsob = request.security(syminfo.tickerid, "60", lsobDetect("1h"))

    if not na(new_lsob)
        new_lsob.startIndex := bar_index
        lsob = Lsob.new(new_lsob, createLsobDraw(new_lsob), createLsobState())
        lsob_records.unshift(lsob)
 
if losbShow and isNew4Hour
    new_lsob = request.security(syminfo.tickerid, "240", lsobDetect("4h"))

    if not na(new_lsob)
        new_lsob.startIndex := bar_index
        lsob = Lsob.new(new_lsob, createLsobDraw(new_lsob), createLsobState())
        lsob_records.unshift(lsob)
 
        // DEBUG
        // debugText = (new_lsob.isBull?'u ':'d ') + str.tostring(new_lsob.min)+"-"+str.tostring(new_lsob.max) + " " + str.tostring(new_lsob.startIndex)
        //debugLabelOffset := debugLabel(debugLabelOffset, debugText)

//debugLabelOffset := debugLabel(debugLabelOffset, str.tostring(lsob_records.size()))
//debugLabelOffset := debugLabel(debugLabelOffset, str.tostring(bar_index))
