
currentHourTime = timestamp("UTC", year, month, dayofmonth, hour, 0)
isNewHour = timeframe.change("60")
isNew4Hour = timeframe.change("240")
hourBars = (60 / timeframe.multiplier)


// =============== COMMONS ===============

alarmLabels = input.bool(true, "Alarm-Labels", group="Debug")

bullBase = input.color(#f4d03f, "Bullish Color", group="Styles")
bearBase = input.color(#d5dbdb, "Bearish Color", group="Styles")

bullCss        = color.new(bullBase, 70)
bearCss        = color.new(bearBase, 70)
bullCssBorder  = color.new(bullBase, 50)
bearCssBorder  = color.new(bearBase, 50)

bullCssLight   = color.new(bullBase, 80)
bearCssLight   = color.new(bearBase, 80)
bullCssBorderLight   = color.new(bullBase, 90)
bearCssBorderLight   = color.new(bearBase, 90)

textColor = input.color(color.white, "Text Color", group="Styles")
noneColor = color.new(color.white, 100)
